#!/usr/bin/env bash
# Copies a file to a server using scp

ARGS_ERROR="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

if (($# < 4)); then
	echo "$ARGS_ERROR"
	exit 1
fi

file_path=$1
ip=$2
user=$3
ssh_path=$4 
target="$user@$ip:~/"

scp -i "$ssh_path" -T "$file_path" "$target" 
