#!/usr/bin/env bash
# Installs and configures nginx on a server to match specifications

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
service nginx restart
echo Hello World! > /var/www/html/index.html
