#!/usr/bin/env bash
# Installs and configures nginx on a server to match specifications

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
service nginx start

redirect="rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
search="server_name _"
sed -i "/$search/a $redirect" /etc/nginx/sites-available/default
nginx -s reload
