#!/usr/bin/env bash
# Installs and configures nginx on a server to match specifications

apt-get -y update
apt-get -y install nginx
service nginx restart

redirect="rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
search="server_name _"
sed -i "/$search/a $redirect" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/404.html
error="\\\terror_page 404 /404.html;\n \\tlocation  /404.html {\n\\t\\tinternal;\n\\t}"
sed -i "/$search/a $error" test

nginx -s reload
