#!/usr/bin/env bash
# Installs and configures HAProxy on a Ubuntu 16.04 server

sudo apt update -y
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt-get install haproxy=2.0.\* -y
echo ENABLED=1 | sudo tee -a /etc/default/haproxy

haprox_fe='
frontend haproxy-main
    bind *:80
    option forwardfor  
    default_backend webservers'    

haprox_be='
backend webservers
    balance roundrobin
    server web-01	54.208.71.151:80 check
    server web-02	100.25.34.99:80 check'

echo "$haprox_fe $haprox_be" | sudo tee -a /etc/haproxy/haproxy.cfg

/etc/init.d/haproxy reload
