#!/usr/bin/env bash
# Displays `To infinity and beyond` indefinitely with a sleep of 2
# between each iteration of the loop.
# Displays 'I am invincible!!!' when receiving a SIGTERM signal

trap "echo I am invincible!!!" SIGTERM

while true
do 
    echo 'To infinity and beyond'
    sleep 2
done