#!/usr/bin/env bash
# Gives information about the `school` file.
f="school"

if [ -e "$f" ]
then
    echo 'school file exists'
    if [ -f "$f" ]
    then    
        echo 'school is a regular file'
    fi
    if [ -s "$f" ]
    then
        echo 'school file is not empty'
    else
        echo 'school file is empty'
    fi
else
    echo 'school file does not exist'
fi