#!/usr/bin/env bash
# Configures an Ubuntu server such that:
#    localhost resolves to 127.0.0.2
#    facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -ri 's/([0-9].+)(\slocalhost)/127.0.0.2\2/g' ~/hosts.new
if grep -q -wi "facebook.com" ~/hosts.new
then
    sed -ri 's/([0-9].+)(\sfacebook.com)/8.8.8.8\2/g' ~/hosts.new
else
echo '8.8.8.8   facebook.com' >> ~/hosts.new
fi
cp -f ~/hosts.new /etc/hosts
